# Generated by Django 5.2.6 on 2025-10-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='telefono',
            field=models.CharField(default='000000000', max_length=15),
        ),
    ]
