# Generated by Django 5.2.6 on 2025-10-16 15:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkinglot_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='parking_images/')),
                ('es_principal', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='parkinglot',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='acepta_reservas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='rating_promedio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='tiene_camaras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='tiene_vigilancia_24h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='total_reseñas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='nivel_seguridad',
            field=models.IntegerField(choices=[(1, 'Básico'), (2, 'Moderado'), (3, 'Alto'), (4, 'Premium'), (5, 'Máxima Seguridad')], default=1),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='precio_hora',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='total_plazas',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='parkinglot',
            index=models.Index(fields=['latitud', 'longitud'], name='parking_par_latitud_9260ca_idx'),
        ),
        migrations.AddIndex(
            model_name='parkinglot',
            index=models.Index(fields=['plazas_disponibles'], name='parking_par_plazas__ba2f78_idx'),
        ),
        migrations.AddIndex(
            model_name='parkinglot',
            index=models.Index(fields=['precio_hora'], name='parking_par_precio__7acb5b_idx'),
        ),
        migrations.AddIndex(
            model_name='parkinglot',
            index=models.Index(fields=['nivel_seguridad'], name='parking_par_nivel_s_e6114e_idx'),
        ),
        migrations.AddIndex(
            model_name='parkinglot',
            index=models.Index(fields=['rating_promedio'], name='parking_par_rating__37ae45_idx'),
        ),
        migrations.AddField(
            model_name='parkingimage',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='parking.parkinglot'),
        ),
        migrations.AddField(
            model_name='parkingreview',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='parking.parkinglot'),
        ),
        migrations.AddField(
            model_name='parkingreview',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
