# Generated by Django 5.2.7 on 2025-10-30 06:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parkingimage_parkingreview_alter_parkinglot_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkinglot',
            options={'ordering': ['-rating_promedio']},
        ),
        migrations.RemoveIndex(
            model_name='parkinglot',
            name='parking_par_latitud_9260ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='parkinglot',
            name='parking_par_plazas__ba2f78_idx',
        ),
        migrations.RemoveIndex(
            model_name='parkinglot',
            name='parking_par_precio__7acb5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='parkinglot',
            name='parking_par_rating__37ae45_idx',
        ),
        migrations.RenameField(
            model_name='parkingimage',
            old_name='parking_lot',
            new_name='estacionamiento',
        ),
        migrations.RenameField(
            model_name='parkinglot',
            old_name='acepta_reservas',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='parkinglot',
            old_name='tiene_camaras',
            new_name='aprobado',
        ),
        migrations.RenameField(
            model_name='parkingreview',
            old_name='parking_lot',
            new_name='estacionamiento',
        ),
        migrations.RenameField(
            model_name='parkingreview',
            old_name='creado_en',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='parkingimage',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='parkingimage',
            name='es_principal',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='precio_hora',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='tiene_vigilancia_24h',
        ),
        migrations.AlterUniqueTogether(
            name='parkingreview',
            unique_together={('usuario', 'estacionamiento')},
        ),
        migrations.AddField(
            model_name='parkingimage',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='coordenadas',
            field=models.CharField(default='0.0,0.0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='tarifa_hora',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingreview',
            name='calificacion',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='nivel_seguridad',
            field=models.CharField(default='Estándar', max_length=50),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Número de teléfono inválido.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='total_plazas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='parkinglot',
            index=models.Index(fields=['direccion'], name='parking_par_direcci_34294a_idx'),
        ),
        migrations.RemoveField(
            model_name='parkingreview',
            name='rating',
        ),
    ]
