# Generated by Django 5.2.7 on 2025-11-01 17:34

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_parkinglot_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('coordenadas', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Número de teléfono inválido.', regex='^\\+?1?\\d{9,15}$')])),
                ('descripcion', models.TextField(blank=True)),
                ('horario_apertura', models.TimeField(default=datetime.time(8, 0))),
                ('horario_cierre', models.TimeField(default=datetime.time(22, 0))),
                ('nivel_seguridad', models.CharField(default='Estándar', max_length=50)),
                ('tarifa_hora', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_plazas', models.PositiveIntegerField()),
                ('plazas_disponibles', models.PositiveIntegerField()),
                ('servicios', models.JSONField(blank=True, default=list)),
                ('panel_local_id', models.CharField(max_length=100)),
                ('notas_aprobacion', models.TextField(blank=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('estacionamiento_creado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_aprobacion', to='parking.parkinglot')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_aprobacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['status'], name='parking_par_status_ee8ad8_idx'), models.Index(fields=['panel_local_id'], name='parking_par_panel_l_59dd82_idx'), models.Index(fields=['fecha_solicitud'], name='parking_par_fecha_s_6ccb6e_idx')],
            },
        ),
    ]
