# Generated by Django 5.2.7 on 2025-10-30 06:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_pago', models.CharField(editable=False, max_length=50, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('moneda', models.CharField(default='PEN', max_length=3)),
                ('metodo', models.CharField(choices=[('tarjeta', 'Tarjeta Crédito/Débito'), ('yape', 'Yape'), ('plin', 'Plin')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('id_transaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('datos_gateway', models.JSONField(blank=True, default=dict)),
                ('comision_plataforma', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('monto_propietario', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_reembolso', models.DateTimeField(blank=True, null=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('ultimo_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('datos_adicionales', models.JSONField(default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
