# Generated by Django 5.2.6 on 2025-09-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('yape', 'Yape'), ('plin', 'Plin'), ('efectivo', 'Efectivo')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
