# Generated by Django 5.2.7 on 2025-10-30 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payments.payment'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['referencia_pago'], name='payments_pa_referen_45449f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='payments_pa_estado_c1aaf3_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['usuario', 'fecha_creacion'], name='payments_pa_usuario_e64ad4_idx'),
        ),
    ]
