# Generated by Django 5.2.7 on 2025-10-30 06:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0004_alter_parkinglot_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('APP', 'Problema con la App'), ('PARKING', 'Problema con un Estacionamiento'), ('PAYMENT', 'Problema con un Pago'), ('OTHER', 'Otro')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En revisión'), ('RESOLVED', 'Resuelto'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('parking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='parking.parkinglot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
