# Generated by Django 5.2.7 on 2025-10-19 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0002_parkinglot_telefono'),
        ('reservations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('license_plate', models.CharField(max_length=10)),
                ('violation_type', models.CharField(choices=[('estacionamiento_prohibido', 'Estacionamiento Prohibido'), ('tiempo_excedido', 'Tiempo Excedido'), ('plaza_incorrecta', 'Plaza Incorrecta'), ('obstruccion', 'Obstrucción de Vía'), ('sin_pago', 'Estacionamiento sin Pago'), ('reserva_incumplida', 'Reserva Incumplida'), ('danio_vehiculo', 'Daño a Vehículo'), ('servicio_deficiente', 'Servicio Deficiente'), ('conducta_inapropiada', 'Conducta Inapropiada'), ('falta_limpieza', 'Falta de Limpieza'), ('otros', 'Otros')], max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('severity', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('resuelta', 'Resuelta'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('parking_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='parking.parkinglot')),
                ('reported_by_parking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_violations', to='parking.parkinglot')),
                ('reported_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_violations', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Infracción',
                'verbose_name_plural': 'Infracciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
